/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dfc.www.private_access.admin.invoice;

import com.fsc.www.db.MC_DB;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepalsuranga
 */
public class jp_invoice_view_invoice extends javax.swing.JPanel {

    String currentDate = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

    /**
     * Creates new form jp_invoice_view_invoice
     */
    public jp_invoice_view_invoice() {
        initComponents();
        md_loadDailyInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tf_invoice_no = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lbl_tot_invoice = new javax.swing.JLabel();
        lbl_tot_invoices_amount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_invoice = new javax.swing.JTable();

        setBackground(new java.awt.Color(251, 140, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoice No:");

        tf_invoice_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_invoice_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_invoice_noActionPerformed(evt);
            }
        });
        tf_invoice_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_invoice_noKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Invoice:");

        lbl_tot_invoice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_tot_invoice.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tot_invoice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_tot_invoice.setText("0");
        lbl_tot_invoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_tot_invoice.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_tot_invoice.setMinimumSize(new java.awt.Dimension(150, 40));

        lbl_tot_invoices_amount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_tot_invoices_amount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tot_invoices_amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_tot_invoices_amount.setText("0.00");
        lbl_tot_invoices_amount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_tot_invoices_amount.setMaximumSize(new java.awt.Dimension(150, 40));
        lbl_tot_invoices_amount.setMinimumSize(new java.awt.Dimension(150, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Cost :");

        tb_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No", "Total", "Qty", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_invoice);
        if (tb_invoice.getColumnModel().getColumnCount() > 0) {
            tb_invoice.getColumnModel().getColumn(0).setPreferredWidth(60);
            tb_invoice.getColumnModel().getColumn(1).setPreferredWidth(40);
            tb_invoice.getColumnModel().getColumn(2).setPreferredWidth(20);
            tb_invoice.getColumnModel().getColumn(3).setPreferredWidth(130);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tot_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl_tot_invoices_amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(tf_invoice_no, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_invoice_no, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbl_tot_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tot_invoices_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_invoice_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_invoice_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_invoice_noActionPerformed

    private void tf_invoice_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_invoice_noKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!tf_invoice_no.getText().isEmpty()) {
                searchCustomInvoice(tf_invoice_no.getText());
            } else {
                viewDailyInvoices();
            }
        }
    }//GEN-LAST:event_tf_invoice_noKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_tot_invoice;
    private javax.swing.JLabel lbl_tot_invoices_amount;
    private javax.swing.JTable tb_invoice;
    private javax.swing.JTextField tf_invoice_no;
    // End of variables declaration//GEN-END:variables

    //search Custom Invoice
    private void searchCustomInvoice(String invoiceNo) {

        DefaultTableModel dtm = (DefaultTableModel) tb_invoice.getModel();
        dtm.setRowCount(0);

        new Thread(() -> {
            try {
                ResultSet rs = MC_DB.search_dataOne("invoice", "invoice_no", invoiceNo);
                if (rs.next()) {
                    Vector v = new Vector();
                    int totQty = getTotalQtyByInvoiceNo(rs.getString("invoice_no"));
                    if (totQty != 0) {
                        v.add(rs.getString("invoice_no"));
                        v.add(rs.getString("total_amount"));
                        v.add(rs.getString("invoice_date"));
                        v.add(totQty);
                        dtm.addRow(v);
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    //search Custom Invoice

    //getTotalQtyByInvoiceNo
    public int getTotalQtyByInvoiceNo(String invoiceNo) {

        try {
            ResultSet rs = MC_DB.search_dataQuery("SELECT COUNT(qty) AS totQty FROM invoice_reg WHERE invoice_no='" + invoiceNo + "'");
            if (rs.next()) {
                return rs.getInt("totQty");
            } else {
                return 0;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }

    }
    //getTotalQtyByInvoiceNo

    //view all daily invoices
    private void viewDailyInvoices() {
        DefaultTableModel dtm = (DefaultTableModel) tb_invoice.getModel();
        dtm.setRowCount(0);
        new Thread(() -> {
            try {
                ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM invoice WHERE invoice_date='" + currentDate + "'");
                while (rs.next()) {
                    Vector v = new Vector();
                    int totQty = getTotalQtyByInvoiceNo(rs.getString("invoice_no"));
                    if (totQty != 0) {
                        v.add(rs.getString("invoice_no"));
                        v.add(rs.getString("total_amount"));
                        v.add(rs.getString("invoice_date"));
                        v.add(totQty);
                        dtm.addRow(v);

                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    //view all daily invoices

    private void md_loadDailyInvoice() {
        try {
            String today_date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            ResultSet rs_invoice = MC_DB.myConnection().createStatement().executeQuery("SELECT * FROM `invoice` WHERE invoice_date='" + today_date + "'");
            DefaultTableModel dtm_inv = (DefaultTableModel) tb_invoice.getModel();
            dtm_inv.setRowCount(0);
            if (rs_invoice != null) {
                while (rs_invoice.next()) {
                    Vector v = new Vector();
                    String invoiceNo=rs_invoice.getString("invoice_id");
                    v.add(rs_invoice.getString("invoice_no"));
                    v.add(rs_invoice.getDouble("total_amount") + "0");

                    ResultSet getQty = MC_DB.search_dataQuery("SELECT SUM(qty) AS totQty FROM invoice_reg WHERE invoice_id='" + invoiceNo+ "'");
                    if (getQty.next()) {
                        v.add(getQty.getInt("totQty"));
                    }
                    ResultSet rs_user = MC_DB.search_dataQuery("SELECT username FROM user_account WHERE user_account_id='"+rs_invoice.getInt("user_account_id")+"'");
                    if(rs_user.next()){
                        v.add(rs_user.getString("username"));
                    }

                    dtm_inv.addRow(v);
                }
                lbl_tot_invoice.setText(dtm_inv.getRowCount() + "");
                double cost = 0;
                for (int i = 0; i < dtm_inv.getRowCount(); i++) {
                    cost += Double.parseDouble(dtm_inv.getValueAt(i, 1).toString());
                }
                lbl_tot_invoices_amount.setText(cost + "0");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
