/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.dfc.www.private_access.admin.cash_account;

/**
 *
 * @author Buwaneka
 */
public class Cash_Account extends javax.swing.JPanel {

    /**
     * Creates new form Cash_Account
     */
    public Cash_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cash_account = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbl_investments = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_income = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Start Date :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 30, 91, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("End Date :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 20, 84, 50);

        tbl_cash_account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Date", "Cash_Type", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_cash_account);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 960, 220);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total Investments :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 340, 180, 30);

        lbl_investments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_investments.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_investments.setText("00.00");
        jPanel1.add(lbl_investments);
        lbl_investments.setBounds(810, 340, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Total Income :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(640, 370, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total Expenses :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(640, 400, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total Profit :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(640, 430, 180, 30);

        lbl_income.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_income.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_income.setText("00.00");
        jPanel1.add(lbl_income);
        lbl_income.setBounds(810, 370, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("00.00");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(810, 400, 170, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("00.00");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(810, 430, 170, 30);

        btn_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.setPreferredSize(new java.awt.Dimension(73, 50));
        jPanel1.add(btn_search);
        btn_search.setBounds(860, 20, 120, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_income;
    private javax.swing.JLabel lbl_investments;
    private javax.swing.JTable tbl_cash_account;
    // End of variables declaration//GEN-END:variables
}
