/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dfc.www.private_access.admin.backend;

import java.awt.Color;
import java.awt.Robot;
import java.awt.event.KeyEvent;

/**
 *
 * @author deepalsuranga
 */
public class jf_onScreenInvoiceKeyBoard extends javax.swing.JFrame {

    /**
     * Creates new form jf_onScreenInvoiceKeyBoard
     */
    public jf_onScreenInvoiceKeyBoard() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.getContentPane().setBackground(new Color(91, 91, 91));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bt_number_7 = new javax.swing.JButton();
        bt_number_8 = new javax.swing.JButton();
        bt_number_9 = new javax.swing.JButton();
        bt_divide = new javax.swing.JButton();
        bt_multi = new javax.swing.JButton();
        bt_number_6 = new javax.swing.JButton();
        bt_number_5 = new javax.swing.JButton();
        bt_number_4 = new javax.swing.JButton();
        bt_number_1 = new javax.swing.JButton();
        bt_number_2 = new javax.swing.JButton();
        bt_number_3 = new javax.swing.JButton();
        bt_substract = new javax.swing.JButton();
        bt_plus = new javax.swing.JButton();
        bt_enter = new javax.swing.JButton();
        bt_number_0 = new javax.swing.JButton();
        bt_space = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setFocusCycleRoot(false);
        setFocusableWindowState(false);

        jPanel2.setBackground(new java.awt.Color(255, 87, 34));

        bt_number_7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_7.setText("7");
        bt_number_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_7ActionPerformed(evt);
            }
        });

        bt_number_8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_8.setText("8");
        bt_number_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_8ActionPerformed(evt);
            }
        });

        bt_number_9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_9.setText("9");
        bt_number_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_9ActionPerformed(evt);
            }
        });

        bt_divide.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_divide.setText("/");
        bt_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divideActionPerformed(evt);
            }
        });

        bt_multi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_multi.setText("*");
        bt_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_multiActionPerformed(evt);
            }
        });

        bt_number_6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_6.setText("6");
        bt_number_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_6ActionPerformed(evt);
            }
        });

        bt_number_5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_5.setText("5");
        bt_number_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_5ActionPerformed(evt);
            }
        });

        bt_number_4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_4.setText("4");
        bt_number_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_4ActionPerformed(evt);
            }
        });

        bt_number_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_1.setText("1");
        bt_number_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_1ActionPerformed(evt);
            }
        });

        bt_number_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_2.setText("2");
        bt_number_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_2ActionPerformed(evt);
            }
        });

        bt_number_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_3.setText("3");
        bt_number_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_3ActionPerformed(evt);
            }
        });

        bt_substract.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_substract.setText("-");
        bt_substract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_substractActionPerformed(evt);
            }
        });

        bt_plus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_plus.setText("+");
        bt_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_plusActionPerformed(evt);
            }
        });

        bt_enter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_enter.setText("Enter");
        bt_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enterActionPerformed(evt);
            }
        });

        bt_number_0.setBackground(new java.awt.Color(51, 51, 51));
        bt_number_0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_number_0.setText("0");
        bt_number_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_number_0ActionPerformed(evt);
            }
        });

        bt_space.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_space.setText("Space");
        bt_space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_spaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_number_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt_number_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt_number_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_number_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt_number_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt_number_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_multi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_number_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt_number_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt_number_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_number_0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_space, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_enter, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(bt_substract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_number_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_number_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_number_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_number_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_number_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_number_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_number_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_number_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_number_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_substract, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_number_0, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(bt_space, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addComponent(bt_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_number_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_7ActionPerformed

        try {
            bt_number_7.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_7);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_7ActionPerformed

    private void bt_number_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_8ActionPerformed

        try {
            bt_number_8.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_8);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_8ActionPerformed

    private void bt_number_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_9ActionPerformed

        try {
            bt_number_9.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_9);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_9ActionPerformed

    private void bt_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divideActionPerformed

        try {
            bt_divide.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_DIVIDE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_divideActionPerformed

    private void bt_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_multiActionPerformed

        try {
            bt_multi.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_MULTIPLY);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_multiActionPerformed

    private void bt_number_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_6ActionPerformed

        try {
            bt_number_6.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_6);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_6ActionPerformed

    private void bt_number_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_5ActionPerformed

        try {
            bt_number_5.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_5);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_5ActionPerformed

    private void bt_number_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_4ActionPerformed

        try {
            bt_number_4.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_4);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_bt_number_4ActionPerformed

    private void bt_number_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_1ActionPerformed

        //        tf_invoice_no.addFocusListener((FocusListener) this);
        //        tf_item_code.addFocusListener((FocusListener) this);
        //        focusGained(this);
        //        if (tf_invoice_no.hasFocus()) {
        //            tf_invoice_no.setText("1");
        //        } else if (tf_item_code.hasFocus()) {
        //            tf_item_code.setText("1");
        //        } else if (tf_qty.hasFocus()) {
        //            tf_qty.setText("1");
        //        } else if (tf_payment.hasFocus()) {
        //            tf_payment.setText("1");
        //        }
        //        Ext.get(document.activeElement).parent().parent().id;
        //        EX
        //        findFocus(this);
        //        Component.get
        //
        //        if (true) {
        //            Component c = (Component).getSource();
        //            Cursor cur = c.getCursor();
        //            c.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //
        //            c.setCursor(cur);
        //
        //        }
        //        System.out.println( KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner());
        //        KeyboardFocusManager=new Robot().mousePress(KeyEvent.VK_1);
        try {
            bt_number_1.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_1ActionPerformed

    private void bt_number_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_2ActionPerformed

        try {
            bt_number_2.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_2);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_2ActionPerformed

    private void bt_number_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_3ActionPerformed

        try {
            bt_number_3.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_3);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_3ActionPerformed

    private void bt_substractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_substractActionPerformed

        try {
            bt_substract.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_SUBTRACT);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_substractActionPerformed

    private void bt_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_plusActionPerformed

        try {
            bt_plus.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_ADD);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_plusActionPerformed

    private void bt_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enterActionPerformed

        try {
            bt_enter.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_ENTER);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_enterActionPerformed

    private void bt_number_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_number_0ActionPerformed

        //        if (tf_invoice_no.hasFocus()) {
        //            tf_invoice_no.setText("0");
        //        } else if (tf_item_code.hasFocus()) {
        //            tf_item_code.setText("0");
        //        } else if (tf_qty.hasFocus()) {
        //            tf_qty.setText("0");
        //        } else if (tf_payment.hasFocus()) {
        //            tf_payment.setText("0");
        //        }
        try {
            bt_number_0.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_number_0ActionPerformed

    private void bt_spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_spaceActionPerformed

        try {
            bt_space.setFocusable(false);
            new Robot().keyPress(KeyEvent.VK_SPACE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_spaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_onScreenInvoiceKeyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_onScreenInvoiceKeyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_onScreenInvoiceKeyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_onScreenInvoiceKeyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jf_onScreenInvoiceKeyBoard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_divide;
    private javax.swing.JButton bt_enter;
    private javax.swing.JButton bt_multi;
    private javax.swing.JButton bt_number_0;
    private javax.swing.JButton bt_number_1;
    private javax.swing.JButton bt_number_2;
    private javax.swing.JButton bt_number_3;
    private javax.swing.JButton bt_number_4;
    private javax.swing.JButton bt_number_5;
    private javax.swing.JButton bt_number_6;
    private javax.swing.JButton bt_number_7;
    private javax.swing.JButton bt_number_8;
    private javax.swing.JButton bt_number_9;
    private javax.swing.JButton bt_plus;
    private javax.swing.JButton bt_space;
    private javax.swing.JButton bt_substract;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
